### PR TITLE
Resolving variables in external files

### PR DESCRIPTION
**Pull request by MikeBeardman**
This change lets the user navigate to the definition of variables defined in other files (which are linked by the Resource keyword)

### CODE REVIEW

**Comment by cluehr** [comment]
Hi there! Is someone reviewing/testing/merging this?

**Comment by mtrubs** [comment]
@MikeBeardman I think you change looks good.  The one question I have is all the code that you removed.  For example 'in keyword/file' variable resolution and linking used to work and doesn't anymore.  Just wondering if something was off in what I am doing.

I think the solution is to keep the previous code and also your code.  I can handle this, but just thought I would mention it.

**Comment by MikeBeardman** [comment]
Hey mtrubs, thanks for merging.. And apologies for disabling your in keyword feature. It was unclear to me what the code was doing.  I looking forward to making further contributions in future, and will be a bit more careful regarding existing features.

**Comment by mtrubs** [comment]
No worries. Thanks for contributing.

**Pull request merged**
